name: CI

on: [push]

jobs:
  composer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Composer install
        uses: php-actions/composer@v6
        with:
          php_version: '8.1'

      - name: Archive build
        run: mkdir /tmp/github-actions/ && tar -cvf /tmp/github-actions/build.tar ./

      - name: Upload build archive for test runners
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: /tmp/github-actions

  behat:
    runs-on: ubuntu-latest
    needs: [composer]

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: /tmp/github-actions

      - name: Extract build archive
        run: tar -xvf /tmp/github-actions/build.tar ./

      - name: Local development server
        run: mkdir www && php -S 0.0.0.0:8080 -t www vendor/phpgt/webengine/go.php &

      - name: Behat tests
        uses: php-actions/behat@v1
        with:
          config: test/behat/behat.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [behat]

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: /tmp/github-actions

      - name: Extract build archive
        run: tar -xvf /tmp/github-actions/build.tar ./

      - uses: php-actions/deploy-ssh@wip
        with:
          # deploy to a subdomain of my personal website (g105b.com)
          hostname: example-deploy-ssh.php-actions.g105b.com
          user: php-actions-deploy-ssh
          path: /var/www/example-deploy-ssh
          ssh_key: ${{ secrets.deploy_ssh_key }}
